sudo: required
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6-dev"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install codecov


script: python -m pytest --verbose --cov cisco_olt_client --cov-report term-missing cisco_olt_client


cache:
  directories:
  - $HOME/.cache/pip


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


after_success:
  - codecov
